export const Icons = {
  back: require('../assets/icons/back.png'),
  car: require('../assets/icons/car.png'),
  cutlery: require('../assets/icons/cutlery.png'),
  donut: require('../assets/icons/donut.png'),
  drink: require('../assets/icons/drink.png'),
  fire: require('../assets/icons/fire.png'),
  fries: require('../assets/icons/fries.png'),
  hamburger: require('../assets/icons/hamburger.png'),
  hotdog: require('../assets/icons/hotdog.png'),
  like: require('../assets/icons/like.png'),
  list: require('../assets/icons/list.png'),
  location: require('../assets/icons/location.png'),
  mastercard: require('../assets/icons/mastercard.png'),
  nearby: require('../assets/icons/nearby.png'),
  noodle: require('../assets/icons/noodle.png'),
  pin: require('../assets/icons/pin.png'),
  pizza: require('../assets/icons/pizza.png'),
  redPin: require('../assets/icons/red-pin.png'),
  riceBowl: require('../assets/icons/rice-bowl.png'),
  salad: require('../assets/icons/salad.png'),
  star: require('../assets/icons/star.png'),
  search: require('../assets/icons/search.png'),
  sushi: require('../assets/icons/sushi.png'),
  user: require('../assets/icons/user.png'),
  shoppingBasket: require('../assets/icons/shopping-basket.png')
}
